apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storage
  hostPath:
    path: kaniko # replace with local directory, such as "/home/<user-name>/kaniko"